services:
  mail2csv:
    build: .
    env_file:
      - .env
    volumes:
      - ./output:/output
    container_name: mail2csv

  mail2csv-exe:
    build:
      context: .
      dockerfile: Dockerfile.exe
    env_file:
      - .env
    volumes:
      - ./output:/app/output
    container_name: mail2csv-exe
